/**
 * Supported merge fields. This deliberately mirrors the original Java enum so
 * template authors can keep using the established [NAME] grammar.
 */
export enum MergeField {
    GAME_NAME = 'GAME_NAME',
    GAME_NAME_FULL = 'GAME_NAME_FULL',
    GAME_PACKAGE = 'GAME_PACKAGE',
    GAME_PACKAGE_FOLDER = 'GAME_PACKAGE_FOLDER',
    JME_VERSION = 'JME_VERSION',
    JME_DEPENDENCIES = 'JME_DEPENDENCIES',
    VR_SPECIALISED_DEPENDENCIES = 'VR_SPECIALISED_DEPENDENCIES',
    ANDROID_SPECIALISED_DEPENDENCIES = 'ANDROID_SPECIALISED_DEPENDENCIES',
    DESKTOP_SPECIALISED_DEPENDENCIES = 'DESKTOP_SPECIALISED_DEPENDENCIES',
    ALL_NON_JME_NON_SPECIALISED_DEPENDENCIES = 'ALL_NON_JME_NON_SPECIALISED_DEPENDENCIES',
    ALL_NON_JME_VERSION_REFERENCES = 'ALL_NON_JME_VERSION_REFERENCES',
    ALL_NON_JME_TOML_LIBRARY_REFERENCES = 'ALL_NON_JME_TOML_LIBRARY_REFERENCES',
    MAVEN_REPOS = 'MAVEN_REPOS',
    TAMARIN_VERSION = 'TAMARIN_VERSION',
    JAVA_VERSION = 'JAVA_VERSION',
    ANDROID_MIN_SDK = 'ANDROID_MIN_SDK',
    RENDERER = 'RENDERER',
    DESKTOP_TARGETS = 'DESKTOP_TARGETS',
    PLATFORMS = 'PLATFORMS',
    REPOSITORIES = 'REPOSITORIES',
    DEPENDENCIES = 'DEPENDENCIES',
    MODULE_LINKS = 'MODULE_LINKS',
    APP_ENGINE_DEPENDENCIES = 'APP_ENGINE_DEPENDENCIES',
    DESKTOP_ENGINE_DEPENDENCIES = 'DESKTOP_ENGINE_DEPENDENCIES',
    ANDROID_ENGINE_DEPENDENCIES = 'ANDROID_ENGINE_DEPENDENCIES',
    IOS_ENGINE_DEPENDENCIES = 'IOS_ENGINE_DEPENDENCIES',
    LIBJGLIOS_PLUGIN_VERSION = 'LIBJGLIOS_PLUGIN_VERSION',
    NATIVE_IMAGE_PLUGIN_VERSION = 'NATIVE_IMAGE_PLUGIN_VERSION',
    FOOJAY_RESOLVER_VERSION = 'FOOJAY_RESOLVER_VERSION',
    ANDROID_GRADLE_PLUGIN_VERSION = 'ANDROID_GRADLE_PLUGIN_VERSION',
    ANDROID_COMPILE_SDK = 'ANDROID_COMPILE_SDK',
    ANDROID_TARGET_SDK = 'ANDROID_TARGET_SDK'
}

export function getMergeFieldInText(field: MergeField): string {
    return `[${field}]`;
}
